name: GTFS Auto-Import

on:
  schedule:
    - cron: '0 2 * * *'  # Exécute à 2h00 tous les jours
  workflow_dispatch:      # Permet l'exécution manuelle

jobs:
  trigger-import:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger GTFS Import
        run: |
          curl -X POST 'https://feemilcayxlszizvedii.supabase.co/functions/v1/cron-gtfs-import' \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" 